name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        arch: [386, amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.16.x'

    - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
      run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o tcp2udp_${{ matrix.os }}_${{ matrix.arch }} .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: tcp2udp_${{ matrix.os }}_${{ matrix.arch }}${{ matrix.os == 'windows-latest' ? '.exe' : '' }}
        path: ./tcp2udp_${{ matrix.os }}_${{ matrix.arch }}${{ matrix.os == 'windows-latest' ? '.exe' : '' }}
