name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        arch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.16.x'

    - name: Build for ${{ runner.os }} ${{ matrix.arch }}
      env:
        GO111MODULE: auto
      run: |
        go build -o tcp2udp_${{ runner.os }}_${{ matrix.arch }} .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: tcp2udp_${{ runner.os }}_${{ matrix.arch }}
        path: ./tcp2udp_${{ runner.os }}_${{ matrix.arch }}
